/* data.jsx — expanded content for Genç TETSİAD v1.1 */

/* ── EVENTS ─────────────────────────────────────────────── */
const PH = (seed, w=800, h=500) => `https://picsum.photos/seed/${seed}/${w}/${h}`;
const EVENTS = [
  { id: 1, day: 22, month: 'NİSAN', tag: 'SAHA GEZİSİ', title: 'İstanbul Fabrika Ziyareti',
    place: 'İstanbul · Beylikdüzü OSB', count: 38, photoLabel: 'FABRİKA İÇİ',
    src: 'uploads/fabrika-ziyareti-grup.jpg',
    speakers: [{ initials: 'AK', name: 'Ahmet Kurt', role: 'Üretim Direktörü' }, { initials: 'SY', name: 'Selin Yıldız', role: 'Kalite Müdürü, İpliksan' }],
    desc: 'Beylikdüzü OSB\'deki iki büyük üretim tesisinde tam günlük teknik gezi. Dokuma, baskı ve konfeksiyon hatları canlı çalışırken incelenecek. Mühendis rehberler eşliğinde Tier-1 tedarik zinciri operasyonu.' },
  { id: 2, day: 14, month: 'MAYIS', tag: 'FUAR', title: 'HOMETEX Fuar Çalışması',
    place: 'CNR Expo · İstanbul', count: 120, photoLabel: 'HOMETEX HALL',
    src: 'uploads/hometex-2026-acilis.jpg',
    speakers: [{ initials: 'RÖ', name: 'Resul Öden', role: 'Genç TETSİAD Başkanı' }, { initials: 'AY', name: 'Aylin Yıldız', role: 'HOMETEX Komite Başkanı' }, { initials: 'MŞ', name: 'Murat Şahinler', role: 'TETSİAD Başkanı' }],
    desc: 'Türkiye ev tekstilinin yıllık vitrini. Genç üyeler için özel stand turu, yurt dışı alıcı görüşmeleri ve networking programı. İlk kez Genç TETSİAD kendi sergi alanı ile katılıyor.' },
  { id: 3, day: 22, month: 'MAYIS', tag: 'ÜNİVERSİTE', title: 'İTÜ Tasarım Etkinlikleri',
    place: 'İTÜ Maçka Kampüsü', count: 64, photoLabel: 'KAMPÜS',
    src: PH('gt-itu-campus'),
    speakers: [{ initials: 'LK', name: 'Prof. Dr. Leyla Karaca', role: 'İTÜ Tekstil Müh.' }, { initials: 'FÖ', name: 'Fatih Özdemir', role: 'ORMEN TEKSTİL' }],
    desc: 'Tekstil mühendisliği öğrencileri ile workshop, mentorluk ve bitirme projesi sunumları. 3 üye firma iş birliği sunum yapacak. Genç TETSİAD İTÜ burs programı da tanıtılacak.' },
  { id: 4, day: 12, month: 'HAZİRAN', tag: 'SAHA GEZİSİ', title: 'Bursa Fabrika Ziyareti',
    place: 'Bursa · DEMİRTAŞ OSB', count: 42, photoLabel: 'DOKUMA',
    src: PH('gt-bursa-weaving'),
    speakers: [{ initials: 'KB', name: 'Kerem Bayraktar', role: 'BAYRAKTAR TEKSTİL CEO' }],
    desc: 'Bursa\'nın köklü dokuma ve baskı fabrikalarında bir tam gün. Polyester dokuma, baskı hattı ve kalite kontrol prosesleri. Saat 09:00 İstanbul servis kalkışı, akşam dönüş.' },
  { id: 5, day: 18, month: 'TEMMUZ', tag: 'SOSYAL', title: 'Gençlik Buluşması',
    place: 'Galataport · İstanbul', count: 95, photoLabel: 'BULUŞMA',
    src: PH('gt-galataport-social'),
    desc: 'Mevsim açılışı; sektörden 200+ genç iş insanı yaz akşamı buluşmasında. Boğaz manzaralı açık alan etkinliği. Networking, müzik ve sektör sohbetleri. Davet ile katılım.' },
  { id: 6, day: 7, month: 'AĞUSTOS', tag: 'TEKNOLOJİ', title: 'Yapay Zekâ Etkinlikleri',
    place: 'Google Türkiye · Levent', count: 56, photoLabel: 'AI LAB',
    src: PH('gt-ai-tech-lab'),
    desc: 'Google Türkiye ev sahipliğinde, üretimde ve pazarlamada yapay zekâ uygulamaları. Vertex AI ile tasarım üretimi demosu, e-ticaret kişiselleştirme vaka çalışmaları. Yarım günlük yoğun program.' },
  { id: 7, day: 15, month: 'EYLÜL', tag: 'ARAŞTIRMA', title: 'Güneydoğu Turu · Etnik Desen',
    place: 'Gaziantep · Şanlıurfa · Mardin', count: 28, photoLabel: 'ANADOLU DESEN',
    src: PH('gt-anadolu-carpet'),
    desc: 'Anadolu motiflerinin çağdaş ev tekstiline taşınması üzerine 4 günlük saha araştırması. El dokuma ustaları ile atölye çalışması, arşiv ziyaretleri ve yerel tedarikçi görüşmeleri.' },
  { id: 8, day: 10, month: 'EKİM', tag: 'ÜNİVERSİTE', title: 'MSGSÜ Tasarım Etkinliği',
    place: 'Mimar Sinan GSÜ · Fındıklı', count: 70, photoLabel: 'STÜDYO',
    src: PH('gt-msgsu-studio'),
    desc: 'Tekstil tasarımı bölümü ile ortak workshop. Genç tasarımcı buluşması, mezuniyet koleksiyonu sunumları ve sektör geri bildirim paneli. Birlikte seçilen 3 proje üretimde hayat bulacak.' },
  { id: 9, day: 14, month: 'KASIM', tag: 'YARIŞMA', title: 'Tasarım Yarışması',
    place: 'İstanbul · Beyoğlu', count: 0, photoLabel: 'JÜRİ SALONU',
    src: PH('gt-design-competition'),
    speakers: [{ initials: 'MŞ', name: 'Murat Şahinler', role: 'Jüri Başkanı' }, { initials: 'DT', name: 'Defne Türkmen', role: 'MSGSÜ' }, { initials: 'EK', name: 'Elena König', role: 'Uluslararası Jüri' }],
    desc: 'Genç tasarımcılar için ulusal yarışma — tema: "2030 Sürdürülebilir Tekstil". 50.000 TL ödül havuzu, jüri: Murat Şahinler, Defne Türkmen ve 3 uluslararası üye. Final sunumları ve gala.' },
  { id: 10, day: 12, month: 'ARALIK', tag: 'ZİRVE', title: 'Gençlik Zirvesi 2026',
    place: 'Wyndham Grand · Levent', count: 0, photoLabel: 'ZİRVE SALONU',
    src: PH('gt-youth-summit-gala'),
    speakers: [{ initials: 'RÖ', name: 'Resul Öden', role: 'Genç TETSİAD Başkanı' }, { initials: 'MŞ', name: 'Murat Şahinler', role: 'TETSİAD Başkanı' }, { initials: 'FÖ', name: 'Fatih Özdemir', role: 'Konsept Mimarı' }],
    desc: 'Yılın kapanışı. "Sektörün Geleceğini Birlikte Yazıyoruz" temalı panel, sergi ve gala akşamı. 2027 yol haritası oylaması, yeni yönetim seçimi ve üye ödülleri. 350 kişi kapasiteli salon.' },
];

const EVENT_FILTERS = ['TÜMÜ', 'FUAR', 'ÜNİVERSİTE', 'SAHA GEZİSİ', 'SOSYAL', 'TEKNOLOJİ', 'ARAŞTIRMA', 'YARIŞMA', 'ZİRVE'];

/* ── MEMBERS ─────────────────────────────────────────────── */
const MEMBERS = [
  { id: 0, initials: 'RÖ', name: 'Resul Öden', firm: 'ÖDEN TEKSTİL', city: 'İstanbul',
    sector: 'Ev Tekstili', position: 'Genel Müdür', bio: 'Genç TETSİAD Başkanı. 28 yaşında sektörün en genç genel müdürü. İhracat hacmini 3 yılda %40 büyüttü.',
    role: 'GENÇ TETSİAD BAŞKANI', gold: true, memberNo: 'TG-2026-0001', phone: '+90 532 101 00 01',
    events: 12, certs: 4, connections: 87 },
  { id: 1, initials: 'FÖ', name: 'Fatih Özdemir', firm: 'ORMEN TEKSTİL', city: 'Ankara',
    sector: 'Döşemelik', position: 'Yönetici · 2. Kuşak', bio: 'Aile şirketinin ikinci kuşağı. Bu uygulamanın gönüllü konsept mimarı. Döşemelik kumaşta B2B toptan.',
    role: 'KONSEPT MİMARI', gold: true, memberNo: 'TG-2026-0342', phone: '+90 542 312 04 60',
    events: 8, certs: 2, connections: 34 },
  { id: 2, initials: 'EY', name: 'Elif Yıldız', firm: 'YILDIZ EV TEKSTİL', city: 'Denizli',
    sector: 'Havlu · Bornoz', position: 'İhracat Direktörü', bio: 'Sürdürülebilir pamuk sertifikasyon sürecini Türkiye\'de öncüledi. Yıllık 12 M$ ihracat.',
    role: 'YÖNETİM', gold: false, memberNo: 'TG-2026-0088', phone: '+90 505 234 56 78',
    events: 6, certs: 3, connections: 52 },
  { id: 3, initials: 'MK', name: 'Mert Kaya', firm: 'KAYA HALI', city: 'Gaziantep',
    sector: 'Makine Halı', position: 'Genel Koordinatör', bio: '3. kuşak halı üreticisi. Anadolu desenlerinin dijital arşivi projesi uluslararası ödül aldı.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0205', phone: '+90 532 345 67 89',
    events: 3, certs: 1, connections: 18 },
  { id: 4, initials: 'ZA', name: 'Zeynep Aydın', firm: 'AYDIN PERDE', city: 'Bursa',
    sector: 'Perdelik', position: 'Tasarım Direktörü', bio: 'Mimarlardan gelen taleplere göre özel koleksiyon geliştiriyor. MSGSÜ mezunu. 14 ülkeye ihracat.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0176', phone: '+90 543 456 78 90',
    events: 5, certs: 1, connections: 27 },
  { id: 5, initials: 'CO', name: 'Can Oktay', firm: 'OKTAY İPLİK', city: 'Uşak',
    sector: 'İplik', position: 'AR-GE Müdürü', bio: 'Geri dönüşümlü PET şişeden iplik üretimi. Türkiye\'nin ilk GRS sertifikalı iplik firmasını kurdu.',
    role: 'YÖNETİM', gold: false, memberNo: 'TG-2026-0114', phone: '+90 507 567 89 01',
    events: 7, certs: 2, connections: 41 },
  { id: 6, initials: 'SD', name: 'Selin Demir', firm: 'DEMİR AKSESUAR', city: 'İstanbul',
    sector: 'Aksesuar', position: 'Kurucu', bio: 'Trend araştırması ve görsel kimlik. Her sezon Heimtextil Frankfurt\'ta koleksiyonunu sunar. MSGSÜ tekstil mezunu.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0389', phone: '+90 530 678 90 12',
    events: 4, certs: 0, connections: 22 },
  { id: 7, initials: 'AT', name: 'Ahmet Tan', firm: 'TAN DOKUMA', city: 'Kahramanmaraş',
    sector: 'Dokuma', position: 'Fabrika Sahibi', bio: 'Klasik atkı dokuma; küçük üretim, butik koleksiyon. Kültürel miras tezgâhlarını koruma vakfı üyesi.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0452', phone: '+90 532 789 01 23',
    events: 2, certs: 1, connections: 14 },
  { id: 8, initials: 'NK', name: 'Nazlı Karaca', firm: 'İTÜ', city: 'İstanbul',
    sector: 'Öğrenci · Tekstil Müh.', position: 'Lisans 3. Sınıf', bio: 'Bitirme projesi: ısı yalıtımlı akıllı kumaş. Genç TETSİAD bursiyeri. Fuarlarda staj yapıyor.',
    role: 'ÖĞRENCİ', gold: false, student: true, memberNo: 'TG-2026-0501', phone: '+90 541 890 12 34',
    events: 2, certs: 0, connections: 9 },
  { id: 9, initials: 'BÇ', name: 'Berk Çelik', firm: 'ÇELIK BOYA', city: 'Bursa',
    sector: 'Boya & Kimya', position: 'Teknik Direktör', bio: 'GOTS ve Oeko-Tex sertifikalı boyama prosesi geliştirdi. 8 patent sahibi. Avrupa\'ya teknik danışmanlık.',
    role: 'YÖNETİM', gold: false, memberNo: 'TG-2026-0067', phone: '+90 505 901 23 45',
    events: 9, certs: 3, connections: 63 },
  { id: 10, initials: 'LA', name: 'Leyla Arslan', firm: 'ARSLAN İHRACAT', city: 'İstanbul',
    sector: 'İhracat & Ticaret', position: 'Kurucu Ortak', bio: 'ABD ve Almanya pazarlarında tekstil aracılık. Yıllık 8M$ hacim. TETSİAD ihracat komitesi üyesi.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0293', phone: '+90 532 012 34 56',
    events: 5, certs: 2, connections: 38 },
  { id: 11, initials: 'KS', name: 'Kaan Sarı', firm: 'SARITEKS', city: 'Kahramanmaraş',
    sector: 'Pamuk İpliği', position: '2. Kuşak Yönetici', bio: 'Organik pamuk üretimini entegre ettiren aile şirketinin ikinci kuşağı. ABD\'li süpermarket zincirleri ile anlaşması var.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0418', phone: '+90 546 123 45 67',
    events: 3, certs: 1, connections: 21 },
  { id: 12, initials: 'DÖ', name: 'Damla Öztürk', firm: 'ÖZ-DES', city: 'Denizli',
    sector: 'Havlucılık', position: 'Üretim Müdürü', bio: 'Sıfır atık üretim modelini 2024\'te uygulamaya aldı. Atık suyu geri dönüştüren ilk Denizli fabrikası.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0331', phone: '+90 542 234 56 78',
    events: 4, certs: 2, connections: 29 },
  { id: 13, initials: 'OE', name: 'Onur Erdem', firm: 'ERDEM HALI', city: 'Gaziantep',
    sector: 'El Dokuma Halı', position: 'Atölye Şefi', bio: 'Geleneksel el dokuma metodlarını Endüstri 4.0 ile harmanlıyor. Avrupa müze ve koleksiyonerlerine satış.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0507', phone: '+90 532 345 67 00',
    events: 2, certs: 0, connections: 11 },
  { id: 14, initials: 'PK', name: 'Pelin Koc', firm: 'ODTÜ', city: 'Ankara',
    sector: 'Öğrenci · End. Tasarım', position: 'Yüksek Lisans', bio: 'Tez konusu: biyobazlı tekstil boyamaları. TÜBİTAK 2210 bursiyer. HOMETEX\'te bitirme sunumu yaptı.',
    role: 'ÖĞRENCİ', gold: false, student: true, memberNo: 'TG-2026-0512', phone: '+90 507 456 78 00',
    events: 1, certs: 0, connections: 7 },
  { id: 15, initials: 'SY', name: 'Selim Yalçın', firm: 'YALÇIN TEKSTİL', city: 'İzmir',
    sector: 'Perde & Döşeme', position: 'Genel Müdür', bio: 'Ege\'nin lider perde üreticisi. İzmir bölge temsilcisi. Otel ve proje mobilyacılarına tedarik.',
    role: 'YÖNETİM', gold: false, memberNo: 'TG-2026-0152', phone: '+90 532 567 89 00',
    events: 6, certs: 2, connections: 44 },
  { id: 16, initials: 'AE', name: 'Ayşe Erdoğan', firm: 'ERDOĞAN BORNOZ', city: 'Denizli',
    sector: 'Bornoz & Plaj', position: 'İş Geliştirme', bio: 'Otel tedarik zinciri uzmanı. Türkiye\'nin 5 yıldızlı otellerinin %30\'una tedarikçi. İtalya distribütörlüğü var.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0234', phone: '+90 543 678 90 00',
    events: 4, certs: 1, connections: 33 },
  { id: 17, initials: 'TG', name: 'Tarık Güneş', firm: 'GÜNEŞ PLASTİK', city: 'İstanbul',
    sector: 'Ambalaj & Aksesuar', position: 'Kurucu', bio: 'Tekstil ürünleri için sürdürülebilir ambalaj. Biyoplastik torba Türkiye\'de ilk. Hollanda ve İsveç\'te satış.',
    role: 'ÜYE', gold: false, memberNo: 'TG-2026-0466', phone: '+90 530 789 01 00',
    events: 3, certs: 1, connections: 16 },
  { id: 18, initials: 'ND', name: 'Naz Doğan', firm: 'Bilkent Üniversitesi', city: 'Ankara',
    sector: 'Öğrenci · İç Mimarlık', position: 'Lisans 4. Sınıf', bio: 'Bitirme projesi: sürdürülebilir konut için tekstil seçim kriterleri. MSGSÜ ile ortak stüdyo.',
    role: 'ÖĞRENCİ', gold: false, student: true, memberNo: 'TG-2026-0523', phone: '+90 541 890 12 00',
    events: 2, certs: 0, connections: 5 },
];

/* ── COURSES ──────────────────────────────────────────────── */
const COURSES = [
  { id: 1, num: 1, cat: 'UZMAN KONUŞMACILAR', title: 'Sektörün önde gelen isimleri',
    sub: 'Aylık seminerler · 9 konuşmacı / yıl', progress: 64, instructor: 'Çeşitli',
    modules: [
      { id: 'm1_1', title: 'Sürdürülebilir Marka Yönetimi', speaker: 'Murat Şahinler', duration: '90 dk', done: true },
      { id: 'm1_2', title: 'İhracatta Dijital Pazarlama', speaker: 'Aylin Yıldız', duration: '75 dk', done: true },
      { id: 'm1_3', title: 'Üretimde Yalın Metodlar', speaker: 'Kerem Bayraktar', duration: '90 dk', done: true },
      { id: 'm1_4', title: 'ESG Raporlama Temelleri', speaker: 'Can Oktay', duration: '60 dk', done: false },
      { id: 'm1_5', title: 'Küresel Tekstil Trendleri', speaker: 'Defne Türkmen', duration: '75 dk', done: false },
    ]},
  { id: 2, num: 2, cat: 'DİJİTAL EĞİTİMLER', title: 'Sosyal medya ve e-ticaret',
    sub: '6 modül · 12 hafta', progress: 38, instructor: 'Burak Yılmaz',
    modules: [
      { id: 'm2_1', title: 'Sosyal Medya Stratejisi', speaker: 'Burak Yılmaz', duration: '2 saat', done: true },
      { id: 'm2_2', title: 'Instagram & LinkedIn B2B', speaker: 'Burak Yılmaz', duration: '90 dk', done: true },
      { id: 'm2_3', title: 'E-ticaret Platform Seçimi', speaker: 'Burak Yılmaz', duration: '60 dk', done: false },
      { id: 'm2_4', title: 'Ürün Fotoğrafçılığı', speaker: 'Stüdyo Ekibi', duration: '3 saat', done: false },
      { id: 'm2_5', title: 'SEO ve İçerik Stratejisi', speaker: 'Burak Yılmaz', duration: '90 dk', done: false },
      { id: 'm2_6', title: 'Reklam Bütçesi Yönetimi', speaker: 'Burak Yılmaz', duration: '60 dk', done: false },
    ]},
  { id: 3, num: 3, cat: 'SÜREÇ EĞİTİMLERİ', title: 'Üretimden pazarlamaya',
    sub: 'Operasyon, lojistik, kalite · 10 hafta', progress: 22, instructor: 'TETSİAD Akademi',
    modules: [
      { id: 'm3_1', title: 'Üretim Planlama Temelleri', speaker: 'TETSİAD Akademi', duration: '2 saat', done: true },
      { id: 'm3_2', title: 'Kalite Kontrol Sistemleri', speaker: 'TETSİAD Akademi', duration: '2 saat', done: false },
      { id: 'm3_3', title: 'Tedarik Zinciri Yönetimi', speaker: 'TETSİAD Akademi', duration: '90 dk', done: false },
      { id: 'm3_4', title: 'Lojistik ve Gümrük', speaker: 'TETSİAD Akademi', duration: '2 saat', done: false },
      { id: 'm3_5', title: 'Pazarlama Kanalları', speaker: 'TETSİAD Akademi', duration: '90 dk', done: false },
    ]},
  { id: 4, num: 4, cat: 'MUHASEBE', title: 'Doğru ticari muhasebe',
    sub: 'Üretici şirketler için pratik · 6 hafta', progress: 0, instructor: 'YMM Ofisi',
    modules: [
      { id: 'm4_1', title: 'Maliyet Muhasebesi Giriş', speaker: 'SMMM Ekibi', duration: '2 saat', done: false },
      { id: 'm4_2', title: 'KDV ve İhracat İstisnaları', speaker: 'YMM Ahmet Bey', duration: '90 dk', done: false },
      { id: 'm4_3', title: 'Nakit Akış Yönetimi', speaker: 'YMM Ahmet Bey', duration: '2 saat', done: false },
      { id: 'm4_4', title: 'Finansal Analiz Araçları', speaker: 'SMMM Ekibi', duration: '90 dk', done: false },
    ]},
  { id: 5, num: 5, cat: 'İLETİŞİM', title: 'Diksiyon ve hitabet',
    sub: 'Sunum ve sahne · 4 hafta', progress: 0, instructor: 'Hülya Mutlu',
    modules: [
      { id: 'm5_1', title: 'Türkçe Diksiyon Temelleri', speaker: 'Hülya Mutlu', duration: '2 saat', done: false },
      { id: 'm5_2', title: 'Sunum Teknikleri', speaker: 'Hülya Mutlu', duration: '2 saat', done: false },
      { id: 'm5_3', title: 'Kamera Önünde Konuşma', speaker: 'Hülya Mutlu', duration: '90 dk', done: false },
      { id: 'm5_4', title: 'Müzakere ve İkna', speaker: 'Hülya Mutlu', duration: '2 saat', done: false },
    ]},
  { id: 6, num: 6, cat: 'ÖZEL TALEPLER', title: 'Üye talebiyle açılan başlıklar',
    sub: 'İhracat, KVKK, ESG · değişken', progress: 0, instructor: 'Davetli uzmanlar',
    modules: [
      { id: 'm6_1', title: 'KVKK Uyum Rehberi', speaker: 'Avukat Zeynep H.', duration: '90 dk', done: false },
      { id: 'm6_2', title: 'ESG Raporlama Pratik', speaker: 'Sürdürülebilirlik Danışmanı', duration: '2 saat', done: false },
      { id: 'm6_3', title: 'Tekstil Sertifikaları (GOTS, OekoTex)', speaker: 'Berk Çelik', duration: '90 dk', done: false },
    ]},
];

/* ── MENTORS ──────────────────────────────────────────────── */
const MENTORS = [
  { id: 1, initials: 'RÖ', name: 'Resul Öden', title: 'Genç TETSİAD Başkanı',
    firm: 'ÖDEN TEKSTİL', city: 'İstanbul',
    expertise: 'Liderlik · Genç Girişimcilik · Vizyon',
    bio: '28 yaşında sektörün en dinamik genel müdürü. Genç TETSİAD\'ı kuran vizyonun sahibi. 3 yılda ihracatı %40 büyüttü.',
    available: 'Ayda 2 görüşme · Online/Yüz yüze', applied: false },
  { id: 2, initials: 'MŞ', name: 'Murat Şahinler', title: 'TETSİAD Başkanı',
    firm: 'ŞAHİNLER HALI', city: 'İstanbul',
    expertise: 'Marka · Uluslararası Strateji · Liderlik',
    bio: 'Ekim 2025 TETSİAD seçiminde başkan seçildi. 25 yıllık sektör deneyimi. 40 ülkeye ihracat portföyü.',
    available: 'Çeyrekte 1 görüşme · Yüz yüze', applied: false },
  { id: 3, initials: 'AY', name: 'Aylin Yıldız', title: 'HOMETEX Komite Başkanı',
    firm: 'HOMETEX FUARCILIK', city: 'İstanbul',
    expertise: 'Fuar Operasyonu · Uluslararası Pazar · B2B',
    bio: '15 yıldır HOMETEX organizasyonu. 120+ ülkeden alıcı ile çalışıyor. Genç firmaları fuara kazandırma programı kurucusu.',
    available: 'Ayda 1 görüşme · Online', applied: false },
  { id: 4, initials: 'KB', name: 'Kerem Bayraktar', title: 'Bayraktar Tekstil CEO',
    firm: 'BAYRAKTAR TEKSTİL', city: 'Bursa',
    expertise: 'Üretim Verimliliği · Yalın Üretim · Otomasyon',
    bio: 'Fabrikasını tam otomasyon ile 5 yılda 3\'e katladı. MIT Sloan sertifikalı. Toyota Üretim Sistemi eğitmeni.',
    available: 'Ayda 2 görüşme · Fabrika ziyareti mümkün', applied: false },
  { id: 5, initials: 'DT', name: 'Defne Türkmen', title: 'Tasarım Direktörü & Akademisyen',
    firm: 'MSGSÜ Tekstil Bölümü', city: 'İstanbul',
    expertise: 'Yüzey Tasarımı · Renk · Koleksiyon Geliştirme',
    bio: 'MSGSÜ Tekstil Tasarımı bölüm başkanı. Milano Moda Haftası\'nda Türkiye standı küratörü. Sektör-akademi köprüsü.',
    available: 'Haftada 1 görüşme · Online', applied: false },
  { id: 6, initials: 'BÇ', name: 'Berk Çelik', title: 'Tekstil Kimyası Uzmanı',
    firm: 'ÇELIK BOYA', city: 'Bursa',
    expertise: 'GOTS · Oeko-Tex · Sürdürülebilir Boyama',
    bio: '8 patent sahibi tekstil kimyacısı. Türkiye\'nin en kapsamlı sertifikalı boyama laboratuvarı. AB düzenlemeleri danışmanlığı.',
    available: 'Çeyrekte 2 görüşme · Laboratuvar turu mümkün', applied: false },
  { id: 7, initials: 'HK', name: 'Hasan Koç', title: 'İhracat Finansmanı Uzmanı',
    firm: 'Eximbank Türkiye', city: 'İstanbul',
    expertise: 'Eximbank Kredileri · Akreditif · Döviz Riski',
    bio: '20 yıl Eximbank\'ta kıdemli uzman. Genç ihracatçı programının mimarı. 500+ firmaya ihracat finansmanı danışmanlığı.',
    available: 'Ayda 3 görüşme · Online', applied: false },
  { id: 8, initials: 'SE', name: 'Seda Ersoy', title: 'Sürdürülebilirlik Danışmanı',
    firm: 'GREEN IMPACT', city: 'İstanbul',
    expertise: 'ESG Raporlama · Karbon Ayakizi · Döngüsel Ekonomi',
    bio: 'Tekstil sektörüne özel ESG danışmanlık firması kurucusu. AB Yeşil Mutabakat\'a uyum alanında Türkiye\'nin öncü ismi.',
    available: 'Ayda 2 görüşme · Online/Yüz yüze', applied: false },
];

/* ── NEWS ─────────────────────────────────────────────────── */
const NEWS = [
  { id: 1, tag: 'HOMETEX 2026', date: '14 MAYIS',
    title: 'Hometex Fuarı kapılarını gençlere açıyor',
    excerpt: 'Bu yıl ilk kez Genç TETSİAD\'a ayrılmış 480 m² sergi alanı. "Sürdürülebilirlik" ve "İnovasyon" temaları altında 28 genç firma vitrin yapacak. Ziyaretçi hedefi 12.000.',
    photoLabel: 'HOMETEX SALON', src: PH('gt-news-hometex', 800, 500),
    body: ['Bu yıl ilk kez Genç TETSİAD\'a ayrılmış 480 m² sergi alanı ile Hometex 2026\'da güçlü bir varlık gösteriyoruz. "Sürdürülebilirlik" ve "İnovasyon" temaları altında 28 genç firma ürünlerini vitrine çıkaracak.', 'Stand tasarımı geri dönüştürülmüş malzemelerden üretildi. Genç TETSİAD alanı, fuarın en çok ziyaret edilen üç stand\'ından biri olmayı hedefliyor. Yurt dışından 3.800 profesyonel alıcı bekleniyor.', 'Üyelerimiz için özel B2B görüşme saatleri ve yurt dışı alıcı yemekleri planlandı. Fuar boyunca her gün 14:00\'de Genç TETSİAD standında kısa networking seansı düzenlenecek.'] },
  { id: 2, tag: 'GENEL KURUL', date: '24 MART',
    title: 'TETSİAD yeni dönem Yönetim Kurulu seçildi',
    excerpt: 'Murat Şahinler başkanlığında 13 aktif komisyon kuruldu. Genç TETSİAD bu yapının en somut çıktısı. 2026-2028 dönemi için 50 milyon dolarlık sektör dönüşüm hedefi belirlendi.',
    photoLabel: 'GENEL KURUL SALONU', src: PH('gt-news-gk'),
    body: ['Murat Şahinler başkanlığında yeni Yönetim Kurulu ilk toplantısını tamamladı. 13 aktif komisyon kuruldu; Genç TETSİAD bu yapının en somut ve en hızlı hayata geçen çıktısı oldu.', '2026-2028 dönemi için belirlenen 50 milyon dolarlık sektör dönüşüm hedefi; sürdürülebilir üretim, dijitalleşme ve yeni nesil marka geliştirme üzerine yoğunlaşıyor.', 'Genel Kurul\'da alınan diğer önemli kararlar arasında üniversite iş birlikleri protokolü, ihracat destek fonu ve Genç TETSİAD burs programı yer aldı.'] },
  { id: 3, tag: 'GENÇ TETSİAD', date: '12 NİSAN',
    title: 'İlk komisyon toplantısı yapıldı',
    excerpt: 'Resul Öden başkanlığında genç temsilciler bir araya geldi. 7 alt komisyon ve 2026 yol haritası onaylandı. Bu uygulama da o toplantıda kararlaştırıldı.',
    photoLabel: 'KOMİSYON TOPLANTISI', src: PH('gt-news-komisyon'),
    body: ['Resul Öden başkanlığında 19 genç temsilcinin katıldığı kuruluş toplantısında 7 alt komisyon oluşturuldu: İhracat & Sürdürülebilirlik, Eğitim & Mentorluk, Ar-Ge & İnovasyon, Tasarım & Moda, Dijital Dönüşüm, Fuar & Etkinlik, Üniversite İlişkileri.', '2026 yol haritası oy birliğiyle onaylandı. Dijital platform olarak bu uygulama da o gün kararlaştırıldı. Konsept mimarı Fatih Özdemir\'e sunum ve geliştirme yetkisi verildi.', 'Toplantı sonunda imzalanan kuruluş bildirgesinde "sektörün geleceğini gençlerle inşa etme" vizyonu resmen tescillendi.'] },
  { id: 4, tag: 'İHRACAT', date: '02 NİSAN',
    title: 'Q1 ihracatımız %12 büyüdü',
    excerpt: 'Türkiye ev tekstili 2026\'nın ilk çeyreğinde 1,4 milyar dolarlık ihracata ulaştı. ABD %22, Almanya %18 ile ilk iki sırada. Yılın tamamı için 5,8 milyar dolar hedefleniyor.',
    photoLabel: 'LİMAN · İHRACAT', src: PH('gt-news-ihracat'),
    body: ['Türkiye ev tekstili 2026\'nın ilk çeyreğinde 1,4 milyar dolarlık ihracat gerçekleştirdi. Bu rakam geçen yılın aynı dönemine göre %12\'lik artışı temsil ediyor.', 'Pazar dağılımında ABD %22 ile liderliğini korurken Almanya %18, İngiltere %14 ile ikinci ve üçüncü sıralarda yer aldı. Körfez ülkelerine ihracat ise geçen yıla göre %28 artarak dikkat çekti.', 'TETSİAD\'ın yıl sonu tahminine göre bu büyüme hızı sürdürülürse 5,8 milyar dolarlık rekor ihracat rakamına ulaşılabilir. Genç TETSİAD üyesi firmalar Q1\'de toplam ihracatın %18\'ini gerçekleştirdi.'] },
  { id: 5, tag: 'SÜRDÜRÜLEBİLİRLİK', date: '20 MART',
    title: 'Yeşil dönüşüm yol haritası açıklandı',
    excerpt: '87 üye firma 2030 yeşil taahhüdünü imzaladı. Hedef: 2030\'a kadar karbon yoğunluğunu %40 azaltmak, geri dönüşümlü hammadde oranını %70\'e çıkarmak.',
    photoLabel: 'YEŞİL ÜRETİM', src: PH('gt-news-sustainability'),
    body: ['TETSİAD\'ın 2030 Yeşil Dönüşüm Yol Haritası kamuoyuyla paylaşıldı. 87 üye firma taahhüdü dijital olarak imzaladı. Hedefler: karbon yoğunluğunu %40 azaltmak, geri dönüşümlü hammadde payını %70\'e çıkarmak, su kullanımını üretim başına %50 düşürmek.', 'Bu hedeflere ulaşmak için 2026-2028 döneminde 120 milyon dolarlık yeşil yatırım planlanıyor. Genç TETSİAD üyeleri, inovatif çözümler getiren girişimler için öncelikli destek alacak.', 'Avrupa\'daki tekstil kuruluşları bu yol haritasını "sektörden gelen en kapsamlı taahhüt" olarak nitelendirdi. AB Yeşil Mutabakat sürecinde Türkiye\'nin referans modeli olarak gösterilmesi bekleniyor.'] },
  { id: 6, tag: 'İŞBİRLİĞİ', date: '08 MART',
    title: 'İTÜ ile akademik protokol imzalandı',
    excerpt: 'Tekstil mühendisliği öğrencileri için Genç TETSİAD bursu ve mentörlük programı başlıyor. Her yıl 5 öğrenciye ücretli staj ve 10 öğrenciye burs imkânı.',
    photoLabel: 'İTÜ İMZA TÖRENİ', src: PH('gt-news-itu-protocol'),
    body: ['Genç TETSİAD ile İstanbul Teknik Üniversitesi arasında imzalanan akademik iş birliği protokolü, sektör-üniversite köprüsünde önemli bir adım. Protokol kapsamında her yıl 5 öğrenciye ücretli sektör stajı, 10 öğrenciye burs imkânı sunulacak.', 'İTÜ Tekstil Mühendisliği Bölümü\'ndeki bitirme projeleri artık Genç TETSİAD üye firmaların gerçek sorunlarına çözüm üretmek üzere tasarlanacak. En iyi 3 proje üretime alınma şansı kazanacak.', 'ODTÜ, Bilkent ve MSGSÜ ile süren görüşmelerin de bu yıl protokole dönüşmesi bekleniyor. Hedef: 2027\'de 8 üniversite, 200 aktif öğrenci iş birliği.'] },
  { id: 7, tag: 'TEKNOLOJİ', date: '01 MART',
    title: 'Yapay zekâ ile tasarım: ilk denemeler',
    excerpt: 'Google Türkiye işbirliğiyle yürütülen pilot projede 6 üye firma yapay zekâ destekli desen üretimi test etti. Ürün geliştirme süresi ortalama %35 kısaldı.',
    photoLabel: 'AI STUDIO', src: PH('gt-news-ai-design'),
    body: ['Google Türkiye ile ortak yürütülen pilot projede 6 Genç TETSİAD üyesi firma, yapay zekâ destekli desen ve koleksiyon geliştirme araçlarını 3 ay boyunca test etti. Sonuçlar umut verici.', 'Ürün geliştirme süresi ortalama %35 kısalırken prototip maliyetleri %22 düştü. En etkileyici sonuç ise "Anadolu motifleri + çağdaş minimalizm" sentezinde elde edildi.', 'Ağustos\'ta Google Türkiye ev sahipliğinde düzenlenecek etkinlikte bu projenin genişletilmiş versiyonu tanıtılacak. Katılım açık, başvurular akademi sekmesinden yapılabilir.'] },
  { id: 8, tag: 'ANADOLU', date: '20 ŞUBAT',
    title: 'Gaziantep halıcılığı UNESCO yolunda',
    excerpt: 'Gaziantep el dokuma halısı kültürel miras başvurusu için Genç TETSİAD destek mektubu verdi. Mert Kaya liderliğindeki çalışma grubu dijital arşivi tamamladı: 4.200 özgün desen.',
    photoLabel: 'GAZIANTEP DOKUMA', src: PH('gt-news-gaziantep'),
    body: ['Gaziantep el dokuma halısı, UNESCO Somut Olmayan Kültürel Miras Listesi\'ne girmek için başvuru sürecini başlattı. Genç TETSİAD, bu tarihi adıma güçlü destek mektubuyla katkı sağladı.', 'Mert Kaya\'nın (KAYA HALI) liderliğini üstlendiği çalışma grubu, 18 ay süren saha araştırmasının ardından 4.200 özgün desen ve 340 usta profili içeren dijital arşivi tamamladı.', 'UNESCO kararı 2027\'de bekleniyor. Başvuru sürecinde Genç TETSİAD, yerel halı kooperatifleri ve Gaziantep Valiliği ile ortak çalışıyor. Bu model diğer Anadolu dokuma gelenekleri için de örnek teşkil ediyor.'] },
  { id: 9, tag: 'EĞİTİM', date: '10 ŞUBAT',
    title: 'Akademi programına kayıt rekoru',
    excerpt: 'Genç TETSİAD Akademi\'nin ilk yılında 6 programın toplam 340 başvurusu oldu. Kontenjan 180\'e yükseltildi.',
    photoLabel: 'AKADEMİ SALONU', src: PH('gt-news-academy'),
    body: ['Genç TETSİAD Akademi\'nin ilk sezonu rekorla kapandı. 6 kurs programına toplam 340 başvuru gelirken kontenjan başlangıçtaki 120\'den 180\'e çıkarıldı.', 'En yoğun talep "Sürdürülebilir Marka Yönetimi" ve "İhracat Finansmanı" programlarına geldi. Online+yüz yüze karma format katılım oranını artırdı: tamamlama oranı %87.', 'TBA (Tekstil Business Academy)\'nın ikinci dönemi için şimdiden 80 ön başvuru alındı. Eğitim komisyonu, 2026-2027 sezonunda 3 yeni kurs ekliyor: Dijital Tekstil Tasarımı, ESG Raporlama, İhracat Hukuku.'] },
  { id: 10, tag: 'ÖDÜL', date: '28 OCAK',
    title: 'Genç TETSİAD\'dan Avrupa\'ya ilk ödül',
    excerpt: 'Can Oktay\'ın kurduğu geri dönüşümlü iplik firması Brüksel\'deki Tekstil İnovasyon Ödülleri\'nde "Sürdürülebilir Süreç" kategorisinde birincilik aldı.',
    photoLabel: 'ÖDÜL TÖRENİ', src: PH('gt-news-award-brussels'),
    body: ['Can Oktay\'ın (OKTAY İPLİK, Uşak) kurduğu geri dönüşümlü PET şişeden iplik üretim firması, Brüksel\'de düzenlenen Avrupa Tekstil İnovasyon Ödülleri\'nde "Sürdürülebilir Süreç" kategorisinde birinci oldu.', 'Türkiye tekstil sektörünün bu prestijli organizasyondaki ilk gençlik ödülü. Jüri kararında "Türkiye\'den gelen bu projenin döngüsel ekonomi yaklaşımı açısından Avrupa sektörüne ilham vereceği" vurgulandı.', 'Ödülün ardından Can Oktay\'a Almanya, Hollanda ve İsveç\'ten 4 iş birliği teklifi geldi. Firma bu yıl GRS sertifikasını tamamlayacak ve kapasitesini iki katına çıkaracak.'] },
  { id: 11, tag: 'FUAR', date: '15 OCAK',
    title: 'Heimtextil Frankfurt: Türkiye güçlü çıktı',
    excerpt: 'Ocak 2026 Frankfurt Heimtextil Fuarı\'na katılan 34 TETSİAD üyesi 180M€ değerinde temas kurdu. Genç TETSİAD stand alanı 3 gün boyunca günde 600+ ziyaretçi aldı.',
    photoLabel: 'FRANKFURT FUAR', src: PH('gt-news-frankfurt'),
    body: ['Ocak 2026 Heimtextil Frankfurt Fuarı\'nda Türkiye yine güçlü bir çıkış yaptı. 34 TETSİAD üyesi firma 180 milyon Euro değerinde ticari temas kurdu.', 'Genç TETSİAD alanı fuar boyunca günde 600\'den fazla ziyaretçi ağırladı. "Sürdürülebilir Türkiye" konseptiyle tasarlanan stand, fuarın en çok fotoğraflanan 5 noktasından biri oldu.', 'Ev tekstili kategorisinde bu yıl Türkiye\'nin pazar payı %9,2\'ye yükseldi. Önümüzdeki yıl daha geniş stand alanı ve Genç TETSİAD özel etkinliği planlanıyor.'] },
  { id: 12, tag: 'ARAŞTIRMA', date: '05 OCAK',
    title: '2026 sektör raporu yayımlandı',
    excerpt: 'TETSİAD\'ın yıllık sektör raporu, Türkiye ev tekstilinin küresel pazar payının %7,3\'e ulaştığını gösteriyor. 10 yılda en yüksek seviye.',
    photoLabel: 'ARAŞTIRMA', src: PH('gt-news-sektorraporü'),
    body: ['TETSİAD\'ın 2026 yıllık sektör raporu yayımlandı. Türkiye ev tekstilinin küresel pazar payı %7,3\'e yükseldi — bu rakam son 10 yılın en yüksek değeri.', 'Raporda öne çıkan bulgular: genç iş insanlarının yönetimindeki firmalar ihracatta %18 daha hızlı büyüdü; sürdürülebilir üretim yapan firmalar premium fiyat farkı elde etti; dijital pazarlama yatırımı yapan üyeler yeni pazar payı kazandı.', '148 sayfalık raporun tam metni üye portalından indirilebilir. Genç TETSİAD\'ın katkısıyla hazırlanan "Genç Girişimci Profili" bölümü bu yıl ilk kez rapora eklendi.'] },
];

/* ── ACTIVITIES ───────────────────────────────────────────── */
const ACTIVITIES = [
  { num: 1, title: 'Üniversiteler & Fabrikalar',
    desc: 'Tekstil bölümlerine sahip üniversitelerle, sektör fabrikalarını buluşturan iki yönlü ziyaret programı. 2026\'da 8 ziyaret planlandı, 4\'ü tamamlandı.' },
  { num: 2, title: 'Gençlik Zirvesi',
    desc: 'Yılın kapanışında düzenlenen büyük buluşma. Panel, sergi ve gala ile genç iş insanlarını bir araya getirir. 2025\'te 280 katılımcı; 2026 hedefi 400 kişi.' },
  { num: 3, title: 'Gençlik Buluşmaları',
    desc: 'Şehir ve fuar üzerinden, küçük gruplar halinde organize edilen düzenli ağ programları. Her buluşmada bir sektör uzmanı konuşma yapar.' },
  { num: 4, title: 'Mentörlük',
    desc: 'Sektörün deneyimli isimleriyle, başvuru üzerine eşleştirme. 8 aktif mentör, yıl boyu birebir görüşmeler. 2025\'te 34 eşleşme yapıldı.' },
];

/* ── GOALS ────────────────────────────────────────────────── */
const GOALS = [
  'Üniversite öğrencileri ile sektörü düzenli biçimde buluşturmak — yılda 6 etkinlik, 3 üniversite.',
  'Genç tasarımcı ve girişimcilere mentörlük sağlamak — yılda 50 eşleşme hedefi.',
  'Sektörün dijital ve sürdürülebilir dönüşümünde öncülük etmek — ESG raporlama standardı.',
  'Üyeler arasında bilgi ve deneyim paylaşımını kurumsallaştırmak — akademi + zirve programı.',
  'HOMETEX Fuarı\'nda gençlik temalı sergi alanları kurmak — yılda 2 özel alan.',
  'Uluslararası fuarlarda Türk ev tekstilini genç yüzlerle temsil etmek — 3 uluslararası fuar / yıl.',
];

/* ── COMMISSIONS ──────────────────────────────────────────── */
const COMMISSIONS = [
  'Sektör Konuları', 'İletişim Medya ve PR', 'Kurumsal İlişkiler', 'Üniversiteler',
  'Üye Kabul', 'Organizasyon ve Etkinlik', 'İhracat Geliştirme',
];

/* ── UNIVERSITIES ─────────────────────────────────────────── */
const UNIS = ['MSGSÜ', 'Boğaziçi', 'Bilkent', 'İTÜ', 'ODTÜ', 'Yalova', 'MEB', 'TMMOB'];

/* ── ABOUT ────────────────────────────────────────────────── */
const ABOUT = {
  tagline: 'Türkiye ev tekstilinin genç iş insanları.',
  founded: '2024',
  parent: 'TETSİAD',
  parentFull: 'Türkiye Ev Tekstili Sanayicileri Derneği',
  parentFounded: '1991',
  desc: 'TETSİAD Yönetim Kurulu kararıyla 2024 yılında kurulan Genç TETSİAD Komisyonu; ev tekstili sektöründe faaliyet gösteren 35 yaş altı genç iş insanlarını, girişimcileri ve öğrencileri bir çatı altında buluşturmaktadır. Bugün 55 il ve 40 ülkede 1.500\'ü aşkın üyesiyle faaliyetlerini sürdürmektedir.',
  mission: 'Genç temsilcileri bir araya getirerek bilgi paylaşımı, eğitim ve mentorluk yoluyla sektörün geleceğini güçlendirmek.',
  vision: 'Ev tekstilinde genç, öncü, yenilikçi ve sürdürülebilir bir ekip olmak.',
  members: 1500,
  cities: 55,
  countries: 40,
  phone: '+90 312 473 04 60',
  email: 'genctetsiad@tetsiad.org',
  address: 'TOBB İkiz Kuleler Binası, Ankara',
  website: 'tetsiad.org',
  social: {
    instagram: '@genctetsiad',
    twitter: '@genctetsiad',
    linkedin: 'company/tetsiad',
    facebook: '@tetsiad.dernek',
  },
};

/* ── PRESIDENT ────────────────────────────────────────────── */
const PRESIDENT = {
  initials: 'RÖ',
  name: 'Resul Öden',
  title: 'GENÇ TETSİAD BAŞKANI',
  firm: 'ROSSA HOME · İSTANBUL',
  quote: 'Genç TETSİAD, sektörün geleceğini bugünden örmeye başlayan bir atölyedir. Üretirken öğrenmek, paylaşırken büyümek istiyoruz.',
  long: 'Türkiye ev tekstilinin dünyada hak ettiği yere ulaşması, yalnızca üretim gücüyle değil, genç kuşağın markalaşma, sürdürülebilirlik ve dijitalleşme alanında ortaya koyacağı vizyonla mümkün olacak. Bu uygulama, o vizyonu bir araya getiren ilk somut adım.',
  message: [
    'Ev tekstili sektörümüz onlarca yıldır dünya pazarında güçlü bir yer tutmaktadır. Ancak bu güç, artık yalnızca üretim kapasitesiyle ölçülmüyor. Tasarım, sürdürülebilirlik, dijitalleşme ve marka değeri; rekabeti şekillendiren yeni eksenler haline geldi.',
    'Genç TETSİAD olarak tam da bu dönüşümün merkezinde yer almak istiyoruz. Türkiye\'nin dokuma geleneğini, genç kuşağın vizyonuyla birleştirdiğimizde ortaya çok güçlü bir sinerji çıkıyor. Sektörün önde gelen ailelerinden gelen genç temsilcileri, üniversite öğrencilerini ve yeni nesil girişimcileri aynı çatı altında buluşturuyoruz.',
    'Bu platform, yalnızca bir uygulama değil; sektörün geleceğine yapılan somut bir yatırım. Her mentorluk programı, her fuar gezisi, her akademik iş birliği — hepsini birlikte inşa ediyoruz. Birlikte öğrenecek, birlikte büyüyeceğiz.',
  ],
  photo: 'GENÇ TETSİAD BAŞKANI · KÜRSÜDE',
};

/* ── SUSTAINABILITY ───────────────────────────────────────── */
const PILLARS = [
  { id: 1, title: 'Sürdürülebilir Üretim', desc: 'Geri dönüşümlü iplik, su tasarrufu, sertifikalı tedarik zinciri.' },
  { id: 2, title: 'Genç Tasarım', desc: 'Kampüslerden sektöre uzanan tasarım köprüsü.' },
  { id: 3, title: 'Dijital Dönüşüm', desc: 'E-ticaret, veri ile karar, üretimde otomasyon.' },
  { id: 4, title: 'Uluslararası Marka', desc: 'Türkiye\'nin dokumasını dünya vitrinine taşımak.' },
];

const SUSTAINABILITY = {
  headline: '2030 Yeşil Dönüşüm Taahhüdü',
  metrics: [
    { id: 1, label: 'Geri dönüşümlü iplik', value: 38, target: 70, unit: '%', delta: '+6 ay' },
    { id: 2, label: 'Su tasarrufu', value: 22, target: 50, unit: '%', delta: '+9 ay' },
    { id: 3, label: 'Enerji yoğunluğu', value: 18, target: 30, unit: '% azalış', delta: '+12 ay' },
    { id: 4, label: 'Sertifikalı tedarik', value: 64, target: 90, unit: '%', delta: '+3 ay' },
  ],
};

/* ── EXPORTS ──────────────────────────────────────────────── */
const EXPORTS = {
  period: 'Q1 · 2026',
  total: '1,4 Mr $',
  growth: '+12%',
  topMarkets: [
    { country: 'ABD', share: 22 },
    { country: 'Almanya', share: 18 },
    { country: 'İngiltere', share: 14 },
    { country: 'Fransa', share: 9 },
    { country: 'Hollanda', share: 7 },
    { country: 'Diğer', share: 30 },
  ],
};

/* ── ANNOUNCEMENTS ────────────────────────────────────────── */
const ANNOUNCEMENTS = [
  { id: 1, priority: 'urgent', author: 'Resul Öden', authorRole: 'GENÇ TETSİAD BAŞKANI', initials: 'RÖ',
    time: '5 dk önce', date: '21 MAYIS · 14:38',
    title: 'Hometex 2026 stand listesi yayımlandı',
    body: 'Genç TETSİAD özel sergi alanı için 28 firmanın katılımı kesinleşti. Stand numaralarını üye panelinizden görebilirsiniz. Bu yıl ilk kez kendi vitrinimizle ev sahibiyiz. Pazar günü kurulum başlıyor.', pinned: true },
  { id: 2, priority: 'high', author: 'Resul Öden', authorRole: 'GENÇ TETSİAD BAŞKANI', initials: 'RÖ',
    time: '2 saat önce', date: '21 MAYIS · 11:50',
    title: 'Sürdürülebilirlik taahhüdü imza süreci',
    body: 'Üye firmalarımız için 2030 yeşil dönüşüm taahhüdü dijital imzaya açıldı. Profilinizin "Belgelerim" bölümünden erişebilirsiniz. Son tarih: 30 Haziran. Taahhüt imzalayanlar HOMETEX\'te özel rozet alacak.' },
  { id: 3, priority: 'normal', author: 'Murat Şahinler', authorRole: 'TETSİAD BAŞKANI', initials: 'MŞ',
    time: 'Dün', date: '20 MAYIS · 18:02',
    title: 'Üretimden markaya — yolculuğumuz başlıyor',
    body: 'Genel Kurul\'da paylaştığım yeni dönem manifestosunun tam metnini "Belgelerim" altına ekledim. Genç TETSİAD bu yolculuğun en somut çıktısı olacak. Okumanızı tavsiye ederim.' },
  { id: 4, priority: 'normal', author: 'Sistem', authorRole: 'GENÇ TETSİAD', initials: 'GT',
    time: '2 gün', date: '19 MAYIS · 09:15',
    title: 'İTÜ etkinliğine 12 kontenjan kaldı',
    body: '22 Mayıs İTÜ Tasarım Etkinlikleri için son kayıtlar alınıyor. Workshop kontenjanı sınırlıdır, kaydınızı Takvim bölümünden yapabilirsiniz.' },
  { id: 5, priority: 'high', author: 'Aylin Yıldız', authorRole: 'HOMETEX KOMİTE', initials: 'AY',
    time: '3 gün', date: '18 MAYIS · 16:40',
    title: 'Fuar refakatçi listesi kapanıyor',
    body: 'Yurt dışı alıcı refakatçi programı için 5 koltuk kaldı. İngilizce iletişim şartı aranmaktadır. Profilinizden başvurunuzu tamamlayın.' },
  { id: 6, priority: 'normal', author: 'Resul Öden', authorRole: 'GENÇ TETSİAD BAŞKANI', initials: 'RÖ',
    time: '5 gün', date: '16 MAYIS · 21:08',
    title: 'Hoş geldiniz — yeni başlıyoruz',
    body: 'Bu uygulama, Genç TETSİAD\'ın sektördeki ilk dijital adımı. Geri bildirimleriniz gelişimimizin temelini oluşturuyor. Sol alttaki Destek menüsünden bize ulaşabilirsiniz.' },
];

/* ── NOTIFICATIONS ────────────────────────────────────────── */
const EVENT_NOTIFICATIONS = [
  { id: 'en1', type: 'event', initials: 'GT', authorRole: 'GENÇ TETSİAD', author: 'Sistem',
    title: 'HOMETEX kaydınız onaylandı',
    body: '14 Mayıs HOMETEX Fuar Çalışması — katılımınız teyit edildi. Stand numaranız: B-247.',
    time: '1 saat önce', date: '21 MAYIS · 13:22', priority: 'high' },
  { id: 'en2', type: 'event', initials: 'GT', authorRole: 'SİSTEM', author: 'Sistem',
    title: 'İTÜ etkinliğine 12 kontenjan kaldı',
    body: '22 Mayıs İTÜ Tasarım Etkinlikleri için kayıt kapanıyor. Son kontenjanı kaçırmayın.',
    time: '3 saat önce', date: '21 MAYIS · 11:02', priority: 'high' },
  { id: 'en3', type: 'event', initials: 'AY', authorRole: 'HOMETEX KOMİTE', author: 'Aylin Yıldız',
    title: 'Fuar refakatçi listesi kapanıyor',
    body: 'Yurt dışı alıcı refakatçi programı için 5 koltuk kaldı. İngilizce şartı.',
    time: '3 gün önce', date: '18 MAYIS · 16:40', priority: 'normal' },
];

const SYSTEM_NOTIFICATIONS = [
  { id: 'sn1', type: 'system', initials: 'GT', authorRole: 'SİSTEM', author: 'Sistem',
    title: 'Üyeliğiniz onaylandı',
    body: 'Üyelik bilgileriniz yönetim kurulu tarafından onaylandı. Üyelik numaranız: TG-2026-0342. Tüm özelliklere erişebilirsiniz.',
    time: '1 hafta önce', date: '14 MAYIS · 09:00', priority: 'normal' },
  { id: 'sn2', type: 'system', initials: 'MŞ', authorRole: 'TETSİAD BAŞKANI', author: 'Murat Şahinler',
    title: 'Bağlantı isteği',
    body: 'Murat Şahinler sizinle LinkedIn\'de bağlantı kurmak istiyor. Profilini inceleyebilirsiniz.',
    time: '2 gün önce', date: '19 MAYIS · 15:30', priority: 'high' },
  { id: 'sn3', type: 'system', initials: 'GT', authorRole: 'SİSTEM', author: 'Sistem',
    title: 'KVKK taahhüdü imza bekleniyor',
    body: '2030 Yeşil Dönüşüm Taahhüdü dijital imzaya açıldı. Son tarih: 30 Haziran.',
    time: '5 gün önce', date: '16 MAYIS · 10:15', priority: 'normal' },
];

/* ── FORM OPTIONS ─────────────────────────────────────────── */
const SECTORS = [
  'Döşemelik', 'Perdelik', 'Havlu · Bornoz', 'Makine Halı',
  'El Dokuma', 'İplik', 'Aksesuar', 'Desen Tasarımı', 'Boya & Kimya',
  'İhracat & Ticaret', 'Ambalaj', 'Diğer',
];

const CITIES = [
  'İstanbul', 'Ankara', 'Bursa', 'Denizli', 'Gaziantep',
  'İzmir', 'Kahramanmaraş', 'Uşak', 'Kayseri', 'Diğer',
];

/* ── PROGRAMS ─────────────────────────────────────────────── */
const PROGRAMS = [
  {
    id: 'ttt',
    abbr: '3T',
    color: 'var(--gold)',
    title: 'Tanı · Tanıştır · Ticaret Yap',
    since: '2024',
    tagline: 'Üyeler arası B2B tekstil ticaret köprüsü.',
    desc: '2024 yılından itibaren hayata geçen ve üyeler arası ticareti geliştirmek adına düzenlenen 3T programı, Genç TETSİAD\'ın en yaygın gerçekleştirilen faaliyetlerinden biridir.',
    body: '3T (Tanı-Tanıştır-Ticaret Yap), ev tekstili sektöründe üyeler arasında aktif iş ilişkilerinin kurulması ve üyelerin ekonomik potansiyeline katkı sağlamayı hedefler. Üretici, ihracatçı, tasarımcı ve bayi firmalarını bir araya getiren program, yeni iş fırsatlarını keşfetme ve ticaret hacmini büyütme imkânı sunar.\n\nGenç TETSİAD\'ın yurt içi fuarlarında (Hometex, Evteks) ve yurt dışı organizasyonlarda (Heimtextil Frankfurt) düzenlenen 3T, ağ oluşturma ve ticareti bir araya getirmek için tasarlanmış bir programdır.',
    tags: ['HOMETEX', 'HEİMTEXTİL', 'EVTEKS', 'B2B EŞLEŞTİRME'],
    cta: '3T\'YE KATIL',
  },
  {
    id: 'tba',
    abbr: 'TBA',
    color: 'var(--gold)',
    title: 'Tekstil Business Academy',
    since: '2025',
    tagline: 'Yılda bir, farklı tekstil merkezinde yoğun eğitim.',
    desc: '2025 yılından itibaren her yıl farklı bir tekstil merkezinde düzenlenen TBA, girişimci ve yenilikçi genç tekstil iş insanlarını yetiştirme merkezidir.',
    body: '2025 yılında Denizli\'de başlayan TBA, 2026\'da Bursa ev sahipliğinde gerçekleşti. Eğitim Komisyonu koordinasyonunda düzenlenen TBA için her yıl son gelişmelere göre yeni bir akademi programı oluşturulur.\n\nSektörün deneyimli isimleri, ihracatçılar, tasarımcılar ve araştırmacılar katılımcılara atölye ortamında eğitim verir. Başvuru sonrası seçilen katılımcılar mülakata davet edilir; uygun adaylara 4 hafta boyunca eğitim verilir. TBA\'yı başarıyla tamamlayanlar katılım sertifikası almaya hak kazanır.\n\nGenç TETSİAD üyeleri TBA eğitimlerine katılmada önceliklidir.',
    topics: [
      'Sürdürülebilir Üretim ve Sertifikasyon',
      'Ev Tekstilinde Marka Yönetimi',
      'İhracat Pazarları ve Alıcı İlişkileri',
      'Dijital Tekstil Tasarımı',
      'Tedarik Zinciri Optimizasyonu',
      'Tekstilde Yapay Zeka Uygulamaları',
      'Halı ve Döşemelik Koleksiyon Geliştirme',
      'E-Ticaret ve Pazar Yeri Yönetimi',
      'GOTS, Oeko-Tex ve Çevresel Sertifikalar',
      'İhracat Finansmanı ve Eximbank',
      'Liderlik ve Kuşak Aktarımı',
      'Girişimcilik Kültürü ve İnovasyon',
    ],
    who: '35 yaş ve altı, ev tekstili sektöründe faaliyet gösteren ya da sektöre yakın çalışan profesyoneller ve üniversite öğrencileri başvurabilir.',
    editions: [
      { num: '01', year: '2025', venue: 'Denizli' },
      { num: '02', year: '2026', venue: 'Bursa' },
    ],
    cta: 'TBA\'YA BAŞVUR',
  },
  {
    id: 'mekik',
    abbr: 'ALTIN MEKİK',
    color: 'var(--gold-bright)',
    title: 'Altın Mekik İhracat Ödülleri',
    since: '2025',
    tagline: '35 yaş altı genç tekstil ihracatçılarının ödül töreni.',
    desc: 'Ülkemiz ekonomisine ihracat yaparak katkı sunan genç tekstilcilerin sayısını artırmak ve gençleri ihracata teşvik etmek amacıyla genç ihracatçıların ödüllendirildiği bir programdır.',
    body: 'Birincisi 2025 yılında gerçekleştirilen ödül töreninde her yıl 8 farklı kategoride ihracatçılara ödül takdimi yapılır.\n\nBu ödül töreni, 35 yaş ve altı genç tekstil ihracatçılarının çeşitli kategorilerde ödüllendirildiği Türkiye\'nin ilk ve tek ev tekstili odaklı gençlik ödül töreni olma özelliğine sahiptir.\n\n*Başvuru için TETSİAD veya Genç TETSİAD üyelik şartı bulunmamakla birlikte bir üyenin referansı olması gerekmektedir.',
    categories: [
      'Havlu & Bornoz',
      'Nevresim & Yatak Örtüsü',
      'Makine Halı',
      'El Dokuma & Kilim',
      'Perdelik & Döşemelik',
      'Teknik Tekstil',
      'Sürdürülebilir Ürün',
      'Yılın Genç İhracatçısı',
    ],
    criteria: [
      '35 yaş ve altında olmak',
      'Ev tekstili sektöründe ihracatçı sıfatına sahip olmak',
      'Şirketini temsil yetkisine sahip olmak',
      'Ödül kapsamında değerlendirilecek firma evraklarını Genç TETSİAD ile paylaşmak',
      'Başvuru sürecinde düzenlenecek etkinliklere katılım göstermek',
    ],
    cta: 'ÖDÜLE BAŞVUR',
  },
  {
    id: 'utgik',
    abbr: 'UTGİK',
    color: 'var(--gold)',
    title: 'Uluslararası Tekstil Gençlik İş Kongresi',
    since: '2026',
    tagline: 'Sektörün en büyük genç iş insanları buluşması.',
    desc: 'Yerli ve yabancı tekstil akademisyenleri ve iş insanlarıyla genç tekstilcileri ve öğrencileri bir araya getiriyor; gençlerin birikimini ve uluslararası bağlarını güçlendiriyoruz.',
    body: 'Genç TETSİAD olarak her yıl düzenlemeyi planladığımız kongre, gençlere ve üniversite öğrencilerine yol göstermek amacıyla, yerli ve yabancı akademisyen ve iş insanlarının tecrübelerini paylaştığı sektörün en önemli gençlik organizasyonlarından biri olmayı hedefliyor.\n\n1. UTGİK, "Sektörün Geleceğini Gençlerle Yazıyoruz" temasıyla 2026 yılında Hometex Fuarı ile eş zamanlı olarak İstanbul\'da gerçekleştirilecek.\n\nGenç TETSİAD bu köklü vizyonun devamlılığını sağlayarak tekstil gençliğine ışık tutmaya ve sektör vizyonu çizmeye devam edecek.',
    editions: [
      { num: '01', year: '2026', theme: 'Sektörün Geleceğini Gençlerle Yazıyoruz', venue: 'İstanbul · Hometex Eş Zamanlı', status: 'PLANLI' },
    ],
    targets: ['%40 Genç İş İnsanı', '%35 Girişimci', '%25 Üniversite Öğrencisi', '2000+ Katılımcı Hedefi'],
    cta: 'KAYIT OL',
  },
];

/* ── INSTAGRAM POSTS ──────────────────────────────────────── */
const INSTAGRAM_POSTS = [
  { id: 'DUQkWi0jeys', type: 'reel', account: 'genctetsiad',
    caption: 'Genç TETSİAD Bursa tanışma yemeğinde Seha Dokuma da yerini aldı.' },
  { id: 'DVHBHFXjOQv', type: 'reel', account: 'genctetsiad',
    caption: 'Genç TETSİAD İhracat Geliştirme Komisyonu Üyesi Osman ile buluşma.' },
  { id: 'DPezklmiRQd', type: 'reel', account: 'tetsiad',
    caption: 'Dünyanın başkenti İstanbul\'da TETSİAD üyelerimiz ile özel bir buluşma.' },
  { id: 'DN0Pmyq2p0h', type: 'reel', account: 'tetsiad',
    caption: 'Sektörümüzü ileri taşıyacak başkan adayımız Murat Şahinler ile gündem değerlendirmesi.' },
  { id: 'DBQp_85tnrS', type: 'post', account: 'tetsiad',
    caption: 'Başkanımız ve sektörümüzün üst düzey isimleri bir arada.' },
  { id: 'C0Tb2SgNXtj', type: 'post', account: 'tetsiad',
    caption: 'TETSİAD Üye Buluşmaları kapsamında İzmir\'de güçlü bir buluşma.' },
];

/* ── EXPORTS ──────────────────────────────────────────────── */
Object.assign(window, {
  EVENTS, EVENT_FILTERS, MEMBERS, COURSES, MENTORS, ACTIVITIES, GOALS, COMMISSIONS, UNIS,
  PRESIDENT, ABOUT, PILLARS, NEWS, ANNOUNCEMENTS, SUSTAINABILITY, EXPORTS,
  EVENT_NOTIFICATIONS, SYSTEM_NOTIFICATIONS, SECTORS, CITIES, PROGRAMS,
  INSTAGRAM_POSTS,
});
